name: kanji_sensei
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  provider: ^6.1.1
  
  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.2.1
  
  # Network & API
  dio: ^5.4.0
  connectivity_plus: ^6.1.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Utils
  get_it: ^8.0.3
  injectable: ^2.3.2
  dartz: ^0.10.1
  logger: ^2.0.2+1
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Code generation
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/login/
    - lib/assets/kanji_data/jlpt_1/
    - lib/assets/kanji_data/jlpt_1_1/
    - lib/assets/kanji_data/jlpt_1_2/
    - lib/assets/kanji_data/jlpt_1_3/
    - lib/assets/kanji_data/jlpt_1_4/
    - lib/assets/kanji_data/jlpt_1_5/
    - lib/assets/kanji_data/jlpt_1_6/
    - lib/assets/kanji_data/jlpt_1_7/
    - lib/assets/kanji_data/jlpt_1_8/
    - lib/assets/kanji_data/jlpt_1_9/
    - lib/assets/kanji_data/jlpt_1_10/
    - lib/assets/kanji_data/jlpt_2/
    - lib/assets/kanji_data/jlpt_2_1/
    - lib/assets/kanji_data/jlpt_2_2/
    - lib/assets/kanji_data/jlpt_2_3/
    - lib/assets/kanji_data/jlpt_3/
    - lib/assets/kanji_data/jlp_3_1/
    - lib/assets/kanji_data/jlpt_3_2/
    - lib/assets/kanji_data/jlpt_3_3/
    - lib/assets/kanji_data/jlpt_4/
    - lib/assets/kanji_data/jlpt_4_1/
    - lib/assets/kanji_data/jlpt_5/
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/assets/fonts/poppins/Poppins-Regular.ttf
        - asset: lib/assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: lib/assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
    - family: Quicksand
      fonts:
        - asset: lib/assets/fonts/quick_sand/Quicksand-Regular.ttf
        - asset: lib/assets/fonts/quick_sand/Quicksand-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/quick_sand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/quick_sand/Quicksand-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/quick_sand/Quicksand-Light.ttf
          weight: 300
